WITH 

prim_amount AS (
	SELECT POLICY_KEY, SUM(PREMIUM_MAX) AS TOTAL_PREMIUM , SUM(ORIGINAL_PREMIUM_MIN) AS TOTAL_ORIGINAL_PREMIUM
	FROM(
		SELECT POLICY_KEY, COVERAGE_ID, MAX(COVERAGE_PREMIUM_AMOUNT) AS PREMIUM_MAX , MIN(PREVIOUS_COVERAGE_PREMIUM_AMOUNT) AS ORIGINAL_PREMIUM_MIN
		FROM DATABASE1.TABLE1
		GROUP BY POLICY_KEY, COVERAGE_ID)
	GROUP BY POLICY_KEY),
	
clients AS (
SELECT DISTINCT (CLIENT_ID), POLICY_KEY, ROLE_TYPE, PERSON_ORG_TYPE, START_DATE, END_DATE, MARITAL_STATUS, ISSUE_DATE
FROM DATABASE2.TABLE2
WHERE ROLE_TYPE = 'Primary Owner'
),
joined AS (
    SELECT 
        DATA.ROW_NUMBER,
        DATA.POLICY_KEY, 
        DATA.COVERAGE_ID,
        DATA.COVERAGE_EFFECTIVE_DATE, 
        DATA.COVERAGE_STATUS_CODE,
        DATA.POLICY_STATUS_CHANGE_DATE,
		DATA.POLICY_PRODUCT_CODE,
		DATA.POLICY_INSURANCE_PRODUCT_CODE,
		DATA.POLICY_INSURANCE_PRODUCT_DESC,
		DATA.POLICY_TYPE_DETAIL,
		DATA.POLICY_SUBPRODUCT,
		DATA.POLICY_ISSUE_DATE,
		DATA.CANCELLATION_DATE,
        DATA.OCCUPATION_CODE,
        DATA.CAPTURE_DATE,
        DATA.SMOKER_CODE,
		DATA.POLICY_STATUS,
        AMOUNT.TOTAL_PREMIUM,
		AMOUNT.TOTAL_ORIGINAL_PREMIUM,
		
		YEAR(DATA.CANCELLATION_DATE) AS CANCEL_YEAR,
		YEAR(CLIENTS.START_DATE) AS START_YEAR,
		CLIENTS.ISSUE_DATE,
		CLIENTS.MARITAL_STATUS,
		CLIENTS.PERSON_ORG_TYPE,
		CLIENTS.CLIENT_ID,
		
        CASE WHEN DATA.CANCELLATION_DATE IS NULL THEN DAYS(CURRENT_DATE) - DAYS(DATA.POLICY_ISSUE_DATE)
         ELSE DAYS(DATA.CANCELLATION_DATE) - DAYS(DATA.POLICY_ISSUE_DATE) 
        END AS DAYS_ACTIVE,

		CASE
		WHEN DATA.CANCELLATION_DATE IS NULL OR (DAYS(DATA.CANCELLATION_DATE) - DAYS(CLIENTS.END_DATE) > 60) THEN 0 
		ELSE 1 
		END AS EXPIRY_FLAG
		
    FROM (DATABASE1.TABLE1 DATA LEFT JOIN 
	prim_amount AMOUNT ON DATA.POLICY_KEY = AMOUNT.POLICY_KEY) LEFT JOIN
	clients CLIENTS ON DATA.POLICY_KEY = CLIENTS.POLICY_KEY
    
    WHERE (DATA.POLICY_PRODUCT_CODE = 'TYPE1' OR DATA.POLICY_PRODUCT_CODE = 'TYPE2' OR DATA.POLICY_PRODUCT_CODE = 'TYPE3') AND
	DATA.SETTLED_FLAG = 1 AND
	(DATA.POLICY_STATUS = 'ENDED' OR DATA.POLICY_STATUS = 'ACTIVE') AND
	BASE_COVERAGE_IND = 'Y' AND 
	BENEFIT_ID= 0 AND
	DATA.CAPTURE_DATE > '2023-04-30' AND
	DATA.CAPTURE_DATE < '2023-06-30' 
),
unique_coverage as (
	SELECT *, ROW_NUMBER() OVER (PARTITION BY CLIENT_ID, POLICY_KEY, COVERAGE_EFFECTIVE_DATE ORDER BY ROW_NUMBER) AS UNIQUE_COVERAGE FROM joined
),
summary as (
	SELECT TEMP1.POLICY_KEY, 
		  TEMP1.CLIENT_ID, 
		  TEMP1.COVERAGE_EFFECTIVE_DATE,
		  TEMP1.POLICY_PRODUCT_CODE,
		  TEMP2.POLICY_PRODUCT_CODE AS PREVIOUS_PRODUCT,
		  TEMP2.POLICY_TYPE_DETAIL AS PREVIOUS_DETAIL,
		  TEMP2.POLICY_INSURANCE_PRODUCT_DESC AS PREVIOUS_DESC,
		  TEMP2.CANCELLATION_DATE
	FROM unique_coverage TEMP1 LEFT JOIN
	 unique_coverage TEMP2 ON 
	 TEMP1.CLIENT_ID = TEMP2.CLIENT_ID AND
	 TEMP2.CANCELLATION_DATE IS NOT NULL AND
	 TEMP2.CANCELLATION_DATE < TEMP1.COVERAGE_EFFECTIVE_DATE AND
	 DAY(TEMP1.COVERAGE_EFFECTIVE_DATE) - DAY(TEMP2.CANCELLATION_DATE) <= 120
	WHERE TEMP1.UNIQUE_COVERAGE = 1 AND TEMP2.UNIQUE_COVERAGE = 1
	),
benefit_summary AS(
SELECT SYSTEM_ID, CONTRACT_ID, COUNT(*) AS BENEFICIARY_COUNT
FROM DATABASE3.TABLE3
WHERE ROLE_DESC = 'Beneficiary - Ordinary' OR 
    ROLE_DESC = 'Beneficiary'
GROUP BY SYSTEM_ID, CONTRACT_ID
),
final_result AS (
	SELECT 
	POLICY_KEY, 
	COVERAGE_EFFECTIVE_DATE,
	ROW_NUMBER() OVER (PARTITION BY CLIENT_ID ORDER BY COVERAGE_EFFECTIVE_DATE DESC) AS ROW_NUMBER_EFFECTIVE
	FROM joined
	WHERE POLICY_STATUS = 'ENDED'
)

SELECT 
RESULTS.*,
DETAILS.PREVIOUS_PRODUCT,
DETAILS.PREVIOUS_DETAIL,
DETAILS.PREVIOUS_DESC,
BENEFIT.BENEFICIARY_COUNT,
CASE 
    WHEN ROW_NUMBER_EFFECTIVE = 1 THEN  1
    ELSE  0
 END AS TARGET_FLAG,
 INTEGER((DAYS(RESULTS.POLICY_ISSUE_DATE) - DAYS(FDS.BIRTH_DATE))/ 365.25) AS AGE_AT_ISSUE
FROM joined RESULTS 
LEFT JOIN summary DETAILS ON
    RESULTS.POLICY_KEY = DETAILS.POLICY_KEY AND
    RESULTS.COVERAGE_EFFECTIVE_DATE = DETAILS.COVERAGE_EFFECTIVE_DATE
LEFT JOIN benefit_summary BENEFIT ON
    RESULTS.CLIENT_ID = BENEFIT.SYSTEM_ID AND
    RESULTS.POLICY_KEY = BENEFIT.CONTRACT_ID
LEFT JOIN DATABASE4.FINAL_TABLE FDS ON
    RESULTS.POLICY_KEY = FDS.POLICY_KEY AND
    RESULTS.COVERAGE_EFFECTIVE_DATE = FDS.COVERAGE_EFFECTIVE_DATE AND
    RESULTS.COVERAGE_ID = FDS.COVERAGE_ID AND
	FDS.BASE_COVERAGE_IND = 'Y'AND 
	FDS.BENEFIT_ID = 0
LEFT JOIN final_result FINAL ON
	RESULTS.POLICY_KEY = FINAL.POLICY_KEY AND
	RESULTS.COVERAGE_EFFECTIVE_DATE = FINAL.COVERAGE_EFFECTIVE_DATE AND 
	FINAL.ROW_NUMBER_EFFECTIVE = 1
