WITH 

prim_amount AS (

	SELECT POL_KEY_ID, SUM(PREM_MAX) AS PREM_SUM , SUM(ORIG_PREM_MIN) AS ORIG_PREM_SUM
	FROM(
		SELECT POL_KEY_ID, CVRG_ID, MAX(CVRG_ANN_PREM_AMT) AS PREM_MAX ,MIN(PREV_CVRG_ANN_PREM_AMT) AS ORIG_PREM_MIN
		FROM LIFE.CSD_HISTORY
		GROUP BY POL_KEY_ID, CVRG_ID)
	GROUP BY POL_KEY_ID),
	
clients AS (
SELECT DISTINCT (ICC_ID), POL_KEY_ID, CONTR_ROLE_TP, PERSON_ORG_CODE, SINCE_DT, EXPIRY_DT, MARITAL_ST_TP,ISSUE_DT--, AGE_AT_SALE
FROM DS_SANDBOX.ICC_FDS_VIEW
WHERE CONTR_ROLE_TP = 'Owner Primary'
),
joined AS (
    SELECT 
        e.ROW_NUM,
        e.POL_KEY_ID, 
        e.CVRG_ID,
        e.CVRG_ISS_EFF_DT, 
        e.CVRG_STS_CD,
        e.POL_STAT_CHNG_DT,
		e.POLPROD_ABBR,
		e.POL_INS_PROD_CD,
		e.POLINS_PROD_DESC_EN,
		e.POLPOL_TYP_DET,
		e.POLSUBPROD,
		e.POL_ISSUE_DT,
		e.CANCEL_DT,
        e.OCCUP_CLASS_CODE,
        e.CAPTURE_DT,
        e.SMOKER_CODE,
		e.POL_STS,
        p.PREM_SUM,
		p.ORIG_PREM_SUM,
		
		YEAR(e.CANCEL_DT) AS CANCEL_YEAR,
		YEAR(D.SINCE_DT) AS SINCE_YEAR,
		D.ISSUE_DT,
		D.MARITAL_ST_TP,
		D.PERSON_ORG_CODE,
		D.ICC_ID,
		
        CASE WHEN e.CANCEL_DT IS NULL THEN DAYS(CURRENT_DATE) - DAYS(e.POL_ISSUE_DT)
         ELSE DAYS(e.CANCEL_DT) - DAYS(e.POL_ISSUE_DT) 
        END AS day_stay,

		CASE
		WHEN e.CANCEL_DT IS NULL OR (DAYS(e.CANCEL_DT) - DAYS(D.EXPIRY_DT) > 60) THEN 0 
		ELSE 1 
		END AS EXPIRY_CANCEL
		
    FROM (LIFE.CSD_HISTORY e LEFT JOIN 
	prim_amount p ON e.POL_KEY_ID = p.POL_KEY_ID)LEFT JOIN
	clients D ON e.POL_KEY_ID = D.POL_KEY_ID
    
    WHERE (e.POLPROD_ABBR = 'TERM' or e.POLPROD_ABBR = 'PERM' or e.POLPROD_ABBR = 'UL') AND
	e.SETTLED = 1 AND

	(e.POL_STS = 'ENDED' OR e.POL_STS = 'INFORCE') AND
	BSE_CVRG_IND = 'Y' AND 
	BNFT_ID= 0 AND
	e.CAPTURE_DT > '2023-04-30' AND
	e.CAPTURE_DT < '2023-06-30' 
),
unicvg as (
	SELECT *, ROW_NUMBER() OVER (PARTITION BY ICC_ID, POL_KEY_ID, CVRG_ISS_EFF_DT ORDER BY ROW_NUM) AS unicvrg FROM joined
),
S as (
	SELECT t1.POL_KEY_ID, 
		  t1.ICC_ID, 
		  t1.CVRG_ISS_EFF_DT,
		  t1.POLPROD_ABBR,
		  t2.POLPROD_ABBR AS prev_prod,
		  t2.POLPOL_TYP_DET AS prev_subpod,
		  t2.POLINS_PROD_DESC_EN AS prev_dtlpod,
		  t2.CANCEL_DT
	FROM unicvg t1 LEFT JOIN
	 unicvg t2 ON 
	 t1.ICC_ID = t2.ICC_ID AND
	 t2.CANCEL_DT IS NOT NULL AND
	 t2.CANCEL_DT < t1.CVRG_ISS_EFF_DT AND
	 DAY(t1.CVRG_ISS_EFF_DT) - DAY(t2.CANCEL_DT) <= 120
	WHERE t1.unicvrg = 1 AND t2.unicvrg = 1
	),
B as (
	SELECT ICC_ID, POLPROD_ABBR, MAX(CANCEL_DT) AS LCXD
	FROM S
	GROUP BY ICC_ID, POLPROD_ABBR
	),
distinc_abbr AS (
	SELECT  S.ICC_ID,
	S.POL_KEY_ID, 
	S.CVRG_ISS_EFF_DT,
	S.prev_prod, 
	S.prev_subpod,
	S.prev_dtlpod
	FROM S LEFT JOIN B ON
	S.ICC_ID = B.ICC_ID AND S.POLPROD_ABBR = B.POLPROD_ABBR AND S.CANCEL_DT = B.LCXD
	WHERE NOT (S.CANCEL_DT IS NOT NULL AND B.LCXD IS NULL)
	),
benefit AS(
SELECT EXT_SYS_ID, ADMIN_CONTRACT_ID, count(*) AS BENE_NUM

FROM LIFE.ICC_FDS_ALL
WHERE CONTR_ROLE_DESC = 'Beneficiary - Ordinary Beneficiary' OR 
    CONTR_ROLE_DESC = 'Beneficiary'

GROUP BY EXT_SYS_ID, ADMIN_CONTRACT_ID
),

ordered AS(
	SELECT 
	POL_KEY_ID, 
	CVRG_ISS_EFF_DT,
	ROW_NUMBER() OVER (PARTITION BY ICC_ID ORDER BY CVRG_ISS_EFF_DT DESC) AS row_num_eff
	FROM joined
	WHERE POL_STS = 'ENDED'
)

SELECT 
o.*
,d. prev_prod
,d. prev_subpod
,d. prev_dtlpod
--,d. TARGETS
,b. BENE_NUM

--FDS

, FDS.ORIG_FRNC_TYP_CD
 ,FDS.TERMINATED
 ,FDS.CLI_CRNT_LOC_CD
 ,FDS.APP_SIGN_LOC_CD
 ,FDS.FBAND
 ,FDS.POL_BILL_TYP_CD
 ,FDS.POL_BILL_MODE_CD
 ,FDS.CVRG_ANN_PREM_AMT
 ,FDS.POL_TOT_BILL_AMT
 ,FDS.CVG_PFEE_AMT
 ,FDS.INS_PROD_CD
 ,FDS.INS_PROD_DESC_EN
 ,FDS.CVG_RIDER_TYP_CD
 ,FDS.CVRG_RT_AGE
 ,FDS.CVG_CLI_ISS_AGE
 ,FDS.CVG_CLI_RT_AGE
 ,FDS.CVG_CLI_SEX_CD
 ,FDS.CVRG_SMKR_CD
 ,FDS.CVG_CLI_SMKR_CD
 ,FDS.CLI_SMKR_CD
 ,FDS.OCCUPATIONDESC
 ,FDS.OCCUP_CLASS_CODE
 ,FDS.CVG_JNT_LIFE_CD
 ,FDS.LRGN_NM
 ,FDS.COUNTRY_ID
 ,FDS.DISCOUNTNAME
 ,FDS.DISCOUNTNAME2
 ,FDS.DISCOUNTNAME3
 ,FDS.POL_DSCNT_GR_CD
 ,FDS.PCT_DSCALC_TYP_CD
 ,FDS.PCT_DSCNT_FCT
 ,FDS.ELIMINATION_PERIOD
 ,FDS.BENEFIT_PERIOD
 ,FDS.POL_REINS_CD
 ,FDS.CSN_TRTY_TYP_CD
 ,FDS.CVG_ORIG_CD
 ,FDS.CVG_BNFT_ORIG_CD
 ,FDS.POL_STDNT_INTV_IND
 ,FDS.GSI_IND
 ,FDS.CVRG_UWGDECN_CD
 ,FDS.INS_CHNL_CD
 ,FDS.CHANNEL
 ,FDS.LPRODORG_TYPE
 ,FDS.FACE_AMT
 ,FDS.ORIG_FACE_AMT
 ,FDS.AGEBAND
 ,FDS.GENDER_CODE
 ,FDS.PROVINCE
 ,FDS.DATE_OF_BIRTH
 ,FDS.CVG_NXT_RENW_DT
 ,FDS.CVG_CNVR_XPRY_DT
 
 ,CASE 
    WHEN row_num_eff = 1 THEN  1
    ELSE  0
 END AS TARGETS
 ,INTEGER((DAYS(o.POL_ISSUE_DT) - DAYS(FDS.DATE_OF_BIRTH))/ 365.25) AS AGE_ISSUE
		--TIMESTAMPDIFF(YEAR, a.DATE_OF_BIRTH, e.POL_ISSUE_DT) AS AGE_ISSUE
		
 ,CASE WHEN o.CANCEL_DT IS NULL THEN INTEGER((DAYS(CURRENT_DATE) - DAYS(FDS.DATE_OF_BIRTH))/ 365.25)	
  ELSE INTEGER((DAYS(o.CANCEL_DT) - DAYS(FDS.DATE_OF_BIRTH))/ 365.25)	
  END AS AGE_RECRD
 ,MONTHS_BETWEEN(FDS.CVG_CNVR_XPRY_DT, o.CANCEL_DT) as MONTHS_UNIL_CVG_CNVR_XPRY_DT
 ,MONTHS_BETWEEN(FDS.CVG_NXT_RENW_DT, o.CANCEL_DT) as MONTHS_UNTIL_CVG_NXT_RENW_DT
 


 ,CASE
    WHEN BENE_NUM = 0 THEN 0
    ELSE 1
 END AS BENE_INDC

FROM joined o 
LEFT JOIN distinc_abbr d ON
    --o.ICC_ID = d.ICC_ID AND 
    o.POL_KEY_ID = d.POL_KEY_ID AND
    o.CVRG_ISS_EFF_DT = d.CVRG_ISS_EFF_DT
LEFT JOIN benefit b ON
    o.ICC_ID = b.EXT_SYS_ID AND
    o.POL_KEY_ID = b.ADMIN_CONTRACT_ID
LEFT JOIN LIFE.FDS_FINALV2 FDS ON
    o.POL_KEY_ID = FDS.POL_KEY_ID AND
    o.CVRG_ISS_EFF_DT = FDS.CVRG_ISS_EFF_DT AND
    o.CVRG_ID = FDS.CVRG_ID AND
	FDS.BSE_CVRG_IND = 'Y'AND 
	FDS.BNFT_ID = 0
LEFT JOIN ordered r ON
	o.POL_KEY_ID = r.POL_KEY_ID AND
	o.CVRG_ISS_EFF_DT = r.CVRG_ISS_EFF_DT and 
	r.row_num_eff = 1
    